image: Ubuntu

version: 3.0.{build}

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+(\.\d+)|(\-[a-z0-9]*)$/

environment:
  NUGET_VERSION: "$APPVEYOR_BUILD_VERSION"

build_script:
- pwsh: echo $env:NUGET_VERSION
- pwsh: cd /home/appveyor/projects/identityserver4-tablestorage/src/Azure.TableStores; dotnet build /p:Version=$env:NUGET_VERSION

test: off

artifacts:
- path: '**\*.nupkg'

deploy:
  provider: NuGet
  server: 
  api_key:
    secure: 99viqiWVQPaeY9G5lppxeEEuUiokzOZ2TwGRIupxRFQuETQrHXtg6zGUy6cCOdkF
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master # only release from master branch
    APPVEYOR_REPO_TAG: true # only release on new tag

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /docs.*/
